version: '3'

services: 
    # payment:
    #     build: ./payment
    #     depends_on: 
    #         - payment_db
    ticket:
        build: ./ticket_order
        restart: always
        depends_on: 
            - ticketdb
    # user:
    #     build: ./user
    #     depends_on:
    #         - user_db
    # paymentdb:
    #     image: postgres
    #     restart: always
    #     environment:
    #         POSTGRES_DB: 'payment'
    #         POSTGRES_PASSWORD: 'root'
    #     ports:
    #         - '5431:5431'
    #     volumes: 
    #         - postgres_payment:/var/lib/postgres
    ticketdb:
        image: postgres
        environment:
            POSTGRES_DB: 'ticket'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: '1234'
        ports:
            - '5432:5432'
        volumes: 
            - ticket-data:/var/lib/postgresql/data
    # userdb:
    #     image: postgres
    #     restart: always
    #     environment:
    #         POSTGRES_DB: 'users'
    #         POSTGRES_PASSWORD: 'root'
    #     ports:
    #         - '5433:5433'
    #     volumes: 
    #         - postgres_user:/var/lib/postgres
    
volumes: 
    postgres_payment:
    ticket-data:
    postgres_user: