version: '3'

services: 
    payment:
        build: ./payment
        restart: always
        ports:
            - '8002:8002'
        depends_on: 
            - paymentdb
    ticket:
        build: ./ticket_order
        restart: always
        ports:
            - '8000:8000'
        depends_on: 
            - ticketdb
    user:
        build: ./user
        restart: always
        ports:
            - '8001:8001'
        depends_on:
            - userdb
    paymentdb:
        image: postgres
        environment:
            POSTGRES_DB: payment
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - '5434:5434'
        volumes: 
            - payment-data:/var/lib/postgres
    ticketdb:
        image: postgres
        environment:
            POSTGRES_DB: ticket
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - '5432:5432'
        volumes: 
            - ticket-data:/var/lib/postgresql/data
    userdb:
        image: postgres
        environment:
            POSTGRES_DB: users
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - '5433:5433'
        volumes: 
            - user-data:/var/lib/postgres
    
volumes: 
    payment-data:
    ticket-data:
    user-data: